console.log ("batir 3 huevos")
console.log ("agregar una taza de azucar")
console.log ("agregar 1/2 taza de aceite")
console.log ("agregar 1 taza de harina leudante")
console.log ("agregar 1/2 taza de leche")
console.log ("agregar escencia de vainilla") 
console.log ("mezclar todos los ingredientes")
console.log ("vertir sobre un molde")
console.log ("prender horno a 180 grados")
console.log ("esperar 90 minutos")
console.log ("sacar la torta y a comer")